--SET foreign_key_checks=0;
--DROP TABLE IF EXISTS BATCH_JOB_EXECUTION, BATCH_JOB_EXECUTION_CONTEXT, BATCH_JOB_EXECUTION_PARAMS, BATCH_JOB_EXECUTION_SEQ, BATCH_JOB_INSTANCE, BATCH_JOB_SEQ, BATCH_STEP_EXECUTION, BATCH_STEP_EXECUTION_CONTEXT, BATCH_STEP_EXECUTION_SEQ CASCADE;
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT(ID INT);
-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ(ID INT);

-- TRUNCATE BATCH_JOB_EXECUTION;
-- TRUNCATE BATCH_JOB_EXECUTION_CONTEXT;
-- TRUNCATE BATCH_JOB_EXECUTION_PARAMS;
-- TRUNCATE BATCH_JOB_EXECUTION_SEQ;
-- TRUNCATE BATCH_JOB_INSTANCE;
-- TRUNCATE BATCH_JOB_SEQ;
-- TRUNCATE BATCH_STEP_EXECUTION;
-- TRUNCATE BATCH_STEP_EXECUTION_CONTEXT;
-- TRUNCATE BATCH_STEP_EXECUTION_SEQ;

--SET foreign_key_checks = 1;
-- customer data
DROP TABLE IF EXISTS PEOPLE;

CREATE TABLE IF NOT EXISTS PEOPLE(
  ID         SERIAL   NOT NULL PRIMARY KEY,
  EMAIL      VARCHAR(255) NOT NULL,
  AGE        INTEGER     NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL
);



